--Uppgift 7 create table mycooltable

USE [NORTHWND]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

Create TABLE [dbo].[MyCoolTable](
	[CoolID] [int] IDENTITY(1,1) NOT NULL,
	[CoolTitle] [nvarchar](25) NOT NULL,
 CONSTRAINT [PK_MyCoolTable] PRIMARY KEY CLUSTERED 
(
	[CoolID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
